"""
This file is automatically generated by the images/_generate_image_data.py script.
"""

from wx.lib.embeddedimage import PyEmbeddedImage


class ImageData(object):

    check_instruments = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAADLElEQVRIiZ2WMWhkVRSG'
        b'v//yCMFiCCnCIinCYrWFZF4hFltYKCgi6XRxZtWwpFBECxe0e/MQ2UJccFFsdklzVbQTG7GVTSHr23ULSSFiEUKKZQiLyBDC'
        b'+y3um8ybTQw7Oc07HM77zzn/PefcK4C8X84DrwPrwJNAZjtICgDYIAGEsW5AE72WXSMdArvAJhCrWIyU98p5xC3MJcQBeN+o'
        b'FkkMLU1TlrHIydtykNVBzBu+B65kiLeAS5a3Za0jtgW1U0bIDbQ0VqbAjbFAJoAyy08JNoVeNfySYTYsRpjL1ddFdSy92eVO'
        b'3htctnx7XMGyYIj0x1nQ0vn5qs0u4pu7cTACbQNDwXKGyRAj2/WZ8rXfsCgRCF7Ke4MriH/Bta25YByMEcwcIO+XF4BrMkEm'
        b'YJ5HWoLUDuCQSQqeWGYBz4AvLS22fr8B/InJLEAKwRCaWmcBB3gH/JyANBXcAT6rYkGiSwjI0rDMXMIq+GOc2lQwQmxUsXg4'
        b'cUn9HSzhx0+evF8+AXxu1EECqQZdq2Jx7xFskAjgNETTIEt5v1z8nxjvARcTLUbmV8T1KY+GIoAgRLuEbm/wDPh32791e+XT'
        b'04EHq9glEJoU9xFvV7H4ZypAA2e7OWAdgS8hfWt0DmkF8UPeL1ebqjpGXyHNjcvH/gS4x6OiyXoJ9qQAiQPBMJVuBCvGP3b7'
        b'5QXwB9jPkuwYbyFuVLE4TqKP5oCQzinZqzjYB9aEquRhBMvYtzEftY7qgWCjioOD4+itOIZgqNstWsViF1jD3DdKIaQFS3ON'
        b'XgMlnLK72hQdrYhWq1ax2EFaE9zXhK7xQP0M3DyRmglDiUa7DkDd7PTQdqpi8bfxyzZHdAFDYKOKxeg0atTwI6kOwKFQENMB'
        b'AO7GwY6kV2y2QA9s3q9isXMaeCOZ0447DMAesACcP8mzisWuxAu2u5LiY4CDWRF0MHvK++VV4FPwlq03Jf6qYnGmuyHvlwH7'
        b'vMWm0EXDh+r2yo7Ed4YXwftCw9RZR/fDVLD2Y6B5AoTxl6QvGhYEPxleE0DeKzuIdzHrhnPjfvdJgDbj+5/mNeOWg9CeYVP4'
        b'iyoOHv4HTyN3/2iuEzYAAAAASUVORK5CYII='
    )

    export_csv = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAADV0lEQVRIiaWVT2hcVRTG'
        b'f7/nUGKog4sQa5EsGhJLKaEziyKCot1YiLYg0k1mI0WoFuJCioiLmVmI+G8liJW60SkWhKLW4kosRerKiQRXQbroohWRUEVC'
        b'CGE+F/PapJlpKHrgwrvv3vt99zvn3HNkiNUb7R2E+chxYNykQIsAhELpBXpAj3BFea3baS4Nw3IIeBHyAXFeWQGWSzCAnoEY'
        b'jEVkXBgNXJPMJv66cLZ5B14xhHQfcEK5BnkiMCVMlmMqMiVOIZMkb5W3nAAuKjNbwSoD8GGfMgKc63ZavwyTvUntbyEQACaU'
        b'7+qN9nPdTrO7nYKi77n8tR14eZt1Ee0PYDdwod5o76812tsRhGBvyNoWcx36u2/JCNlN8jVh+i4EKQDcCOx2tkLSs8RPgn2e'
        b'PcrpWqNdGYhBbrkouQf8XEHnSMaQilgJPATMQ2bE8cEgQyGAAxk8YN1OawU4t/V/vdF6NnFXpHLXGPxPW5VgKKw12iPCaWBv'
        b'oGKohowJN9E/ywPLJKAPAmtJ1tRRYB1YASohpxY6rW6p4OfgHqBWCLuAI8BBYA14EalFPwXqCZdJjiMvAyNJrgpvBqZDrgLt'
        b'wEHwsc0SBAxUUk5IVtCjyAHxHcgjCcvoe8RDgaMmE8gqcVGyGPiSMCbZGb3t7r7YPvBtf0cXFzrNP4C3A8eCj6M7hRnkW5Kf'
        b'ohVxPzJO/IH4I2QWxU1x041ZYVnvTFk2wj8QTBBGQr4AXlE/Fs6TjAJPYs4oq5FDSSBsUpB+LejnfHolw4F6o70fmRNfQj8j'
        b'+Rt4tQxykfISSWa7ndb1hLpxQobkXemmonzuPfqP5ALJC8Bywki0MFSBq+gbyvMo6FP1uVZDORnZ0XcRa3e4SAj0KsDvIa+L'
        b'jxoK8JmQw+pl4BN0Epgsz360EUBrwHXhfWAV/Wqzi0AQKt1OswecubVYm2s1hMMJFxfONt/dqvxezE1VYKBUqOsBdEivuEdL'
        b'WUTNsIZD1kuq+/8rgTAC9MJQApcka0mO1RvtzwlL3S199m5Wn2sXwBGS6cCieH1Y069APkw4gd4EloW12y+ejZR08LsQJsq9'
        b'c91O8/x9WwluLF7qPTzz9Pf2U28vZEysAlWhmqSqVIEq4Y5v5AFwyXAS+ebG4qX8C7bLc9zJ6EyLAAAAAElFTkSuQmCC'
    )

    export_instrument = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACL0lEQVRIia2VP2sUURTF'
        b'f2czLIJBLCxWsZAUMUVY2EFSSIpYJdgYCVaOH8JPsDulVT6B3S4IEoIpBGOTymKLXTCNpFayhaCNIAvxWLyZ/Z/NrHiry5t7'
        b'z7n3vHvfiIJWe95Yk/QWA/Cs06p/KZJXKkogadewjli32C2aV5gAXMYGjKD83wmMkAgcC1hUNFAYBiTFWRaQKDcjFY9eSCJs'
        b'whRpqWjeYhItUnpm/yQR5qJo9FQHcZKuAe9sR5JedJr1TwFWKL9csTQS/xC7BfQtPek2xxdwqgPbO4ZVpBXgIE7SzYCZSTQi'
        b'U5ykm4YDS/eQVoV3JvGmCCQdy/Syga8Ah3GSPhgpAcxFdnYoqIQRpgc6nsKbPACoJWlV8AFcCV3xHWhLPA7roPfGGzK3so56'
        b'NtvdVv1zIYLQfmMDdGC4O5ngkUTDV8Fep1lvz8IpBbB0SqpOs9G22RP0ZCOye8j8bJt78mzwHHOplqSvsI/uVLdWzk9PjkaD'
        b'eqcn325XH31EegpeHrYhJOWydCbBa0n6WuZNpbp1Q3GS/gBuAn+A651m/fc8uXSFLHGSXjP8AkqCnyV7sAsl45mbHeTynvAZ'
        b'cCb7Us0NkexSuCNH0XCs57+Q3VajDdyfGzRJ5rFN1uUjtagpe9wlIo+/Yctxkg4rYGwcByM637wclj5ET0p0PlbIDF+htOGv'
        b'bcofocok6ucQRarMMZRVdoXfj4B94CVQVvYl72qmRPawUDPP74P2/wLIYu0REsnklAAAAABJRU5ErkJggg=='
    )

    open_config = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACOElEQVRIidWVP2sUURTF'
        b'f2cYJIUsQSzEQlJIsAq4WCmkELGwEAu7HRE/gqRKNTN+AbuAoEh0FxQbC0kl+QBBdmGxtIgiIYgasJAQljkWb2ZnNmyTsdFb'
        b'zLu8+979c867d+B/FwF0kxzgLPg0KMJEiAlwaPNtNEiL1gG6Sb5kvIlZlcAGKRiNAH8S6g376U6bAJHNY1mrkgBRraDqexF4'
        b'1k2yTrsKevkPxBmX+QbnrsxlKS5AqWFfogAK20VIhgIDYgyMh/30eIDsALFYHgIL5DrGHKmONnVDISkHPxr2sxoiKkima8De'
        b'Kvc0q8/bs4SkCFizuTRbQZIfAIvHc7Nd8jGrz+Q8F1K/N9oVfAY24nD52D2VfNg1E64xq/maq98QDiGla3FZWg2qwLAPWkfs'
        b'EkgsKnsAsq600oNLRYZI0BE8B67ETcLK9Auhh8NB+oqW0k3ym0AH2IpmnQPwBdhq6xzA9j0gMryMgQBRWSz229Eg+9XWeTfJ'
        b'O8Btw55gO2pwh2AiafAXyYO5g93Bfjfspz+j6esLNH3AfGzr+3Ivj43vIyaSNgHi2iwEb4aD9LBtAIll0FVgbHsMAf9qFE+M'
        b'W7+cUu7aXgBejwbZ7xDAHJXG7VE/22vruZvkF4AHQkfAi2o/BnaAW8C5bpI9KZsqVGVVbdzQpxI11gXgus158NNRP9uvA4g1'
        b'YAlYMaxIoSs17UA3RlSlK8wnGrp0BN5AWm9mUf0yTwHLhrg5lk4oX4f99PvJr/3r8gex6e+LR2Pc0wAAAABJRU5ErkJggg=='
    )

    save_config = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACRUlEQVRIia2WMWsUQRzF'
        b'f29YrghBJFiISLgitXBXWfgVIoltrhOsBLG0yl3hJwgWNlaJXyBgYS2oCEmTykKCiKQIQTAEkWOfxczu7G2iG8m9apibee//'
        b'3vxn5zQcTa4bPxdaAxaAYHOMPMUggYmQKQ1Iwo4/CrDpSSwB7zBP9nY2v1DtGWyMtyQ9JuOD8TroNxdAgKEQLIOD0ang2Oal'
        b'xJrNocQqcLC3vUmBdD9uNY4Eh/vb46OLyCsMR5MV4CMQBK/2tjcfDjYmnwEk+sa7QqvAQVCMpSLPefwDjuUEz6z11DhGZ/qY'
        b'3cFovFIAIVpXlUHZJSA7INV5tfZX6Au2gpOAU12XsqCKJa93KswzHLpXyARklDKyux04ZaOGmBzJs3QcF1ayVzmUQ7eBnEN9'
        b'DlEtn2VCgCahAd0YjiZdGt9trxvWwS+SqyXVEtmJhhvjn4jFLK0S+8DwA7rjSugJ7jq2bS4VTgun29jwFSzdaU61bTdTabfE'
        b'RRGd2xrvQ2Pes2vaUfxtDFAo650YBpgT5FKorOqJh9quDYgdErDKVFkALQKfgGXbFI3CjvZ3xl+5Os6Go8k3w7Ik6utuPJ0D'
        b'eQ0l1qC6/3XZjulEdWJOn4m5EVcQ+d2oL5ndbrgriwDODprX/6pw9QFsRjTv+psRRQfzVWhEZP9KM51f0f9ASPzTAumN4ZHg'
        b'5mA0uS04S4vK9uVNfyTOo35LHIR6hlsxIt4WwDNBATwQvDecyi4zccrTIMVnREkpzqexjUQwLAiu2X6N9PQPhTEDM93XSYAA'
        b'AAAASUVORK5CYII='
    )

    settings = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC/0lEQVRIia2Vv4sdVRTH'
        b'P9/L8JAYgoQlKAb9B7R4UxhBRCSlVRoJZCCYRqKGRRYJW8i8wcLGaBWsIgbmYSdia5Gk20LnEX+ABAwhphBZRJawLI/lfi3u'
        b'fe/Nc7Oa1Zxi5szcy/fc8/2ee47KavQM1ifGJaiQCADYIGGMzNwHEGAUNN8DwjGtEDFTxPeY1QJ0GfGc0AfAJhBtIymDKSZg'
        b'k/HJ8QLzPYsnUCBWgHXEpwXmBeO1yXjU8gitrJodzKVgGEj67VGCA2B+Nx7MOI9/iz6w/brgOPBlNx7dOjC+2AWFwoakIgyr'
        b'BsFh4KKkd4A74AvDM80Jia2s6bwAElLPhwi+37UjZCIiFFmgCCB4EfsGYgC6CHwG/CD8K84yZq1lZyYWPtIU9AqwMftfeB4c'
        b'DJ3geWDN9nlJr2aNXjZszUpRfUrtiJTesAu+l2KlIxfgoFxik7aeArfKM827Em9hnpbUdG29cWANEiMUmnk968b1NvDRv4Fk'
        b'zY4ab0/a0c6eCJjgfBMPamXVBOFLhp+EvhtWTdlfl9KjADOjqKya4zbngMclQj+5nh/yryOG0zJvGk5JjMuq+Qq43LX1vQVF'
        b'LDJIgvIUcCgB7RMifR1JbYQ/JLaAQzbHwI+Rd9qm6Kc1aevbwPmHpKgAriCuYu8gnZ2M6+vLNIlg79H4oaxr613gDcEJpGHX'
        b'LoPP8iwk9ohcVs3AcFrwJPB119Y/7xMkAnf2O4TNMkXDqilkjtm+gHQOuAusDqvmJPi+WL6ViDwvFJ2GRJTYzNkhiWK5lVAi'
        b'vhEcNqwDnwM3sW9KwnaczQnn6hOKTr0sAlPQa8BGn6JILj1BZ3uItCa8anNSYoB4Cfhz0d8WA6nvk7DuLlHU5z+ndrusmvdA'
        b'v0g8i3l/Mq6/3Y/nf7AgKRa5cYX+StfW28DH/wF0KYBtAngKHP2fYA+yJwRTlVVzDVjBrKM09DHRynNIs57P8oV5wCU3BEwQ'
        b'rCA+NGwWpJt7BfFFf7MA53ffT6Kmb3IF7vERxj8Kvf0XZZBevdZw5vgAAAAASUVORK5CYII='
    )

    show_log = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACPElEQVRIiaWWvW4TQRSF'
        b'vzNauWIpSMsT0NlP4TegSBp3adNQBdkWLhAUtOnSJAU9QjyF8xJpQeKnstAeipnZnbV3jQVXsvZ49s6de889MzsCmF2snwCX'
        b'NgvBc0TAxhJgZDqMADAk1MMN8AjcAjfbu+UvpeAfMfMYuJg5HugU+2x4GYBLYI4cjNsItjPo4bhMufwongsug80CCDE7bYzP'
        b'gFqoNq6FethQA7XxED4DNjYYB9sLTS/W3wVP47o+e7hbfTudhUObXayfAV9THT8CEFJwhHb/EzzZLtMlCJUceZf7XtPz1U+J'
        b'SUttFBEps7LZy+396m1vsnPCUFlJeIqD2SRNgEkcp/UpYuS/1V5spM4xlN2Xywgexikzsa+ortDsA1DJRH68l6JUGyMLITK2'
        b'emwh+H2wyikUYb8CQtuclIgSNypWmJ2vm+39cjNEUVWy2aMIXqc+YLublCOXbMo7YNOnKKKg1tN4X0qJ5xjbufby1UFiphu3'
        b'XSpA9PIXb0CBATOpIre46TlILVWVDbn6Xg/Qu6GDzqlhBh7ul8Mbs6XUVF0/vO8UN1pbUHrG1LJ0jx6uNkcpKtRcDOtQKUNO'
        b'p1C0UzGqVv0p+2MLnELR9m5Zj0c4zTJFSQFCdJz/qwkmBUVNRfyGvkjvr6bnqw9SPLYHVfS34HCVKbJ5rIgf6Pdp6rXEdXGe'
        b'l5Pjs6+icQyNxG0w3ACfQE13To7/cvloHDtuvC/AjaC4tuCFrHhtGaPIbqWK2ceN0aOKa8sf0WEmVNYH1mUAAAAASUVORK5C'
        b'YII='
    )

    start = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACPklEQVRIia2TP2gUURDG'
        b'f99xaAhWFmIVLMT+HhbWqcRKLES4tRdLIWATN0uKYJFKCxEbdQOKWAhCxMKAFv5BVi0ECxELCwmWQSRIPot9t7d7uYt3SQYe'
        b'M+y+nfnmN7MCCEl20vZjoa+IReBlkadb7IO1SufTkmYQs5hV4G5IsmMhyfangM1BMMYgpoAE/Ba4GpJses8FJFoGBNgGDHDE'
        b'sGT8KSTZ2U53ob37DqAlBAhJsVT15DjwSNKTTnchdLqTYStnYFqmUh69a9fcBs4gXgHLIckOT1RAEqrnrmo4njKWmRa+Yvtz'
        b'SLLLIcmmxuugrAIIBEZYKp+pGcdz1HADWAtJNhu62cj5xBk05Yuovmdu4IqzcQt8Clg13A9JNjMaEeoncT9JD1E9xnHT4phs'
        b'HxC+UGJbyDoD82lVfjJE295LOmR0DXgdkuxcSMq1jj/arhCNik+AH9o6D9Cuf9goouEx1R8Zrw+Ly8am+ohE1KHKjzqo1Fvh'
        b'2R5/B10E7g100JQn96THgdZiSTgOv4ql34KbwHKRp+u9jO1SuyqGla9jqcc1GtE2gafAXJGn3xiwdl35IN5hJvUa0pbt98Lz'
        b'Qi+KPP077H67DmZcRIh10KKkO0We/tlBT+zAgMZAZDaQbguWijz9tVPiRgFVWzQCkdmUeI6YBz4WeTpO7n4Bm63+rjcRGX8R'
        b'mgOejeI8RgfDtkg/DdeFbhUrO3P+fwd4UxER9oakBzYZ4sckOEZ3gNaAS4J3oEXgzYeVvSXu2T998Bm7mZIDIAAAAABJRU5E'
        b'rkJggg=='
    )

    stop = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAABSElEQVRIie2VTU7DMBCF'
        b'v2d5gXoEjsF5uEKFkDgA+657VxZVHwv/jUOTFonssJTkix175r1MYr28fn7Yekc8CRLlAAMiGSMD0tW1XyrDE8NV5VqncgFO'
        b'GfQm8QzzKO1pFLgsSBuOHFq4PyabQ1vZuI/abjBxz7dns86GQ5aKJS1x20hDesu4sQ3IY71tzpnquWrqinbcOPfx6MsGp66e'
        b'KP++FfH5VTYpq3arexSuK0GM0YOcrWpPkO56vyi7qcW+NQZI4LTMUlXf6J6VlCr2XQbIilXRLfIUZBnwlxZp+mj2sGgx7a8t'
        b'mmKHILrNc5Vts23yyEw/5t5q4wtvBb7NaVIfVMhDcmQq2/cZTBq/htE5XrqH9IWuR/4UNv8WbTNoX4uA674WeWeLJF0yZfff'
        b'xSLBVwZO4CPoIEh4sQ8zc9uz2360wRfQ+RtXGSpcSutTWgAAAABJRU5ErkJggg=='
    )


if __name__ == '__main__':

    import wx

    _app = wx.App(redirect=False)

    print(ImageData.check_instruments.Bitmap)
    print(ImageData.export_csv.Bitmap)
    print(ImageData.export_instrument.Bitmap)
    print(ImageData.open_config.Bitmap)
    print(ImageData.save_config.Bitmap)
    print(ImageData.settings.Bitmap)
    print(ImageData.show_log.Bitmap)
    print(ImageData.start.Bitmap)
    print(ImageData.stop.Bitmap)
