"""
This file is automatically generated by the images/_generate_image_data.py script.
"""

from wx.lib.embeddedimage import PyEmbeddedImage


class ImageData:

    check_instruments = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAADLElEQVRIiZ2WM'
        b'WhkVRSGv//yCMFiCCnCIinCYrWFZF4hFltYKCgi6XRxZtWwpFBECxe0e/MQ2UJccFFsdklzVbQTG7GVTSHr23ULSS'
        b'FiEUKKZQiLyBDC+y3um8ybTQw7Oc07HM77zzn/PefcK4C8X84DrwPrwJNAZjtICgDYIAGEsW5AE72WXSMdArvAJhC'
        b'rWIyU98p5xC3MJcQBeN+oFkkMLU1TlrHIydtykNVBzBu+B65kiLeAS5a3Za0jtgW1U0bIDbQ0VqbAjbFAJoAyy08J'
        b'NoVeNfySYTYsRpjL1ddFdSy92eVO3htctnx7XMGyYIj0x1nQ0vn5qs0u4pu7cTACbQNDwXKGyRAj2/WZ8rXfsCgRC'
        b'F7Ke4MriH/Bta25YByMEcwcIO+XF4BrMkEmYJ5HWoLUDuCQSQqeWGYBz4AvLS22fr8B/InJLEAKwRCaWmcBB3gH/J'
        b'yANBXcAT6rYkGiSwjI0rDMXMIq+GOc2lQwQmxUsXg4cUn9HSzhx0+evF8+AXxu1EECqQZdq2Jx7xFskAjgNETTIEt'
        b'5v1z8nxjvARcTLUbmV8T1KY+GIoAgRLuEbm/wDPh32791e+XT04EHq9glEJoU9xFvV7H4ZypAA2e7OWAdgS8hfWt0'
        b'DmkF8UPeL1ebqjpGXyHNjcvH/gS4x6OiyXoJ9qQAiQPBMJVuBCvGP3b75QXwB9jPkuwYbyFuVLE4TqKP5oCQzinZq'
        b'zjYB9aEquRhBMvYtzEftY7qgWCjioOD4+itOIZgqNstWsViF1jD3DdKIaQFS3ONXgMlnLK72hQdrYhWq1ax2EFaE9'
        b'zXhK7xQP0M3DyRmglDiUa7DkDd7PTQdqpi8bfxyzZHdAFDYKOKxeg0atTwI6kOwKFQENMBAO7GwY6kV2y2QA9s3q9'
        b'isXMaeCOZ0447DMAesACcP8mzisWuxAu2u5LiY4CDWRF0MHvK++VV4FPwlq03Jf6qYnGmuyHvlwH7vMWm0EXDh+r2'
        b'yo7Ed4YXwftCw9RZR/fDVLD2Y6B5AoTxl6QvGhYEPxleE0DeKzuIdzHrhnPjfvdJgDbj+5/mNeOWg9CeYVP4iyoOH'
        b'v4HTyN3/2iuEzYAAAAASUVORK5CYII='
    )

    export_csv = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAADV0lEQVRIiaWVT'
        b'2hcVRTGf7/nUGKog4sQa5EsGhJLKaEziyKCot1YiLYg0k1mI0WoFuJCioiLmVmI+G8liJW60SkWhKLW4kosRerKiQ'
        b'RXQbroohWRUEVCCGE+F/PapJlpKHrgwrvv3vt99zvn3HNkiNUb7R2E+chxYNykQIsAhELpBXpAj3BFea3baS4Nw3I'
        b'IeBHyAXFeWQGWSzCAnoEYjEVkXBgNXJPMJv66cLZ5B14xhHQfcEK5BnkiMCVMlmMqMiVOIZMkb5W3nAAuKjNbwSoD'
        b'8GGfMgKc63ZavwyTvUntbyEQACaU7+qN9nPdTrO7nYKi77n8tR14eZt1Ee0PYDdwod5o76812tsRhGBvyNoWcx36u'
        b'2/JCNlN8jVh+i4EKQDcCOx2tkLSs8RPgn2ePcrpWqNdGYhBbrkouQf8XEHnSMaQilgJPATMQ2bE8cEgQyGAAxk8YN'
        b'1OawU4t/V/vdF6NnFXpHLXGPxPW5VgKKw12iPCaWBvoGKohowJN9E/ywPLJKAPAmtJ1tRRYB1YASohpxY6rW6p4Of'
        b'gHqBWCLuAI8BBYA14EalFPwXqCZdJjiMvAyNJrgpvBqZDrgLtwEHwsc0SBAxUUk5IVtCjyAHxHcgjCcvoe8RDgaMm'
        b'E8gqcVGyGPiSMCbZGb3t7r7YPvBtf0cXFzrNP4C3A8eCj6M7hRnkW5KfohVxPzJO/IH4I2QWxU1x041ZYVnvTFk2w'
        b'j8QTBBGQr4AXlE/Fs6TjAJPYs4oq5FDSSBsUpB+LejnfHolw4F6o70fmRNfQj8j+Rt4tQxykfISSWa7ndb1hLpxQo'
        b'bkXemmonzuPfqP5ALJC8Bywki0MFSBq+gbyvMo6FP1uVZDORnZ0XcRa3e4SAj0KsDvIa+LjxoK8JmQw+pl4BN0Epg'
        b'sz360EUBrwHXhfWAV/Wqzi0AQKt1OswecubVYm2s1hMMJFxfONt/dqvxezE1VYKBUqOsBdEivuEdLWUTNsIZD1kuq'
        b'+/8rgTAC9MJQApcka0mO1RvtzwlL3S199m5Wn2sXwBGS6cCieH1Y069APkw4gd4EloW12y+ejZR08LsQJsq9c91O8'
        b'/x9WwluLF7qPTzz9Pf2U28vZEysAlWhmqSqVIEq4Y5v5AFwyXAS+ebG4qX8C7bLc9zJ6EyLAAAAAElFTkSuQmCC'
    )

    export_instrument = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACL0lEQVRIia2VP'
        b'2sUURTFf2czLIJBLCxWsZAUMUVY2EFSSIpYJdgYCVaOH8JPsDulVT6B3S4IEoIpBGOTymKLXTCNpFayhaCNIAvxWL'
        b'yZ/Z/NrHiry5t7z7n3vHvfiIJWe95Yk/QWA/Cs06p/KZJXKkogadewjli32C2aV5gAXMYGjKD83wmMkAgcC1hUNFA'
        b'YBiTFWRaQKDcjFY9eSCJswhRpqWjeYhItUnpm/yQR5qJo9FQHcZKuAe9sR5JedJr1TwFWKL9csTQS/xC7BfQtPek2'
        b'xxdwqgPbO4ZVpBXgIE7SzYCZSTQiU5ykm4YDS/eQVoV3JvGmCCQdy/Syga8Ah3GSPhgpAcxFdnYoqIQRpgc6nsKbP'
        b'ACoJWlV8AFcCV3xHWhLPA7roPfGGzK3so56NtvdVv1zIYLQfmMDdGC4O5ngkUTDV8Fep1lvz8IpBbB0SqpOs9G22R'
        b'P0ZCOye8j8bJt78mzwHHOplqSvsI/uVLdWzk9PjkaDeqcn325XH31EegpeHrYhJOWydCbBa0n6WuZNpbp1Q3GS/gB'
        b'uAn+A651m/fc8uXSFLHGSXjP8AkqCnyV7sAsl45mbHeTynvAZcCb7Us0NkexSuCNH0XCs57+Q3VajDdyfGzRJ5rFN'
        b'1uUjtagpe9wlIo+/Yctxkg4rYGwcByM637wclj5ET0p0PlbIDF+htOGvbcofocok6ucQRarMMZRVdoXfj4B94CVQV'
        b'vYl72qmRPawUDPP74P2/wLIYu0REsnklAAAAABJRU5ErkJggg=='
    )

    open_config = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACOElEQVRIidWVP'
        b'2sUURTFf2cYJIUsQSzEQlJIsAq4WCmkELGwEAu7HRE/gqRKNTN+AbuAoEh0FxQbC0kl+QBBdmGxtIgiIYgasJAQlj'
        b'kWb2ZnNmyTsdFbzLu8+979c867d+B/FwF0kxzgLPg0KMJEiAlwaPNtNEiL1gG6Sb5kvIlZlcAGKRiNAH8S6g376U6'
        b'bAJHNY1mrkgBRraDqexF41k2yTrsKevkPxBmX+QbnrsxlKS5AqWFfogAK20VIhgIDYgyMh/30eIDsALFYHgIL5DrG'
        b'HKmONnVDISkHPxr2sxoiKkima8DeKvc0q8/bs4SkCFizuTRbQZIfAIvHc7Nd8jGrz+Q8F1K/N9oVfAY24nD52D2Vf'
        b'Ng1E64xq/maq98QDiGla3FZWg2qwLAPWkfsEkgsKnsAsq600oNLRYZI0BE8B67ETcLK9Auhh8NB+oqW0k3ym0AH2I'
        b'pmnQPwBdhq6xzA9j0gMryMgQBRWSz229Eg+9XWeTfJO8Btw55gO2pwh2AiafAXyYO5g93Bfjfspz+j6esLNH3AfGz'
        b'r+3Ivj43vIyaSNgHi2iwEb4aD9LBtAIll0FVgbHsMAf9qFE+MW7+cUu7aXgBejwbZ7xDAHJXG7VE/22vruZvkF4AH'
        b'QkfAi2o/BnaAW8C5bpI9KZsqVGVVbdzQpxI11gXgus158NNRP9uvA4g1YAlYMaxIoSs17UA3RlSlK8wnGrp0BN5AW'
        b'm9mUf0yTwHLhrg5lk4oX4f99PvJr/3r8gex6e+LR2Pc0wAAAABJRU5ErkJggg=='
    )

    save_config = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACRUlEQVRIia2WM'
        b'WsUQRzFf29YrghBJFiISLgitXBXWfgVIoltrhOsBLG0yl3hJwgWNlaJXyBgYS2oCEmTykKCiKQIQTAEkWOfxczu7G'
        b'2iG8m9apibee//3vxn5zQcTa4bPxdaAxaAYHOMPMUggYmQKQ1Iwo4/CrDpSSwB7zBP9nY2v1DtGWyMtyQ9JuOD8Tr'
        b'oNxdAgKEQLIOD0ang2OalxJrNocQqcLC3vUmBdD9uNY4Eh/vb46OLyCsMR5MV4CMQBK/2tjcfDjYmnwEk+sa7QqvA'
        b'QVCMpSLPefwDjuUEz6z11DhGZ/qY3cFovFIAIVpXlUHZJSA7INV5tfZX6Au2gpOAU12XsqCKJa93KswzHLpXyARkl'
        b'DKyux04ZaOGmBzJs3QcF1ayVzmUQ7eBnEN9DlEtn2VCgCahAd0YjiZdGt9trxvWwS+SqyXVEtmJhhvjn4jFLK0S+8'
        b'DwA7rjSugJ7jq2bS4VTgun29jwFSzdaU61bTdTabfERRGd2xrvQ2Pes2vaUfxtDFAo650YBpgT5FKorOqJh9quDYg'
        b'dErDKVFkALQKfgGXbFI3CjvZ3xl+5Os6Go8k3w7Ik6utuPJ0DeQ0l1qC6/3XZjulEdWJOn4m5EVcQ+d2oL5ndbrgr'
        b'iwDODprX/6pw9QFsRjTv+psRRQfzVWhEZP9KM51f0f9ASPzTAumN4ZHg5mA0uS04S4vK9uVNfyTOo35LHIR6hlsxI'
        b't4WwDNBATwQvDecyi4zccrTIMVnREkpzqexjUQwLAiu2X6N9PQPhTEDM93XSYAAAAAASUVORK5CYII='
    )

    settings = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC/0lEQVRIia2Vv'
        b'4sdVRTHP9/L8JAYgoQlKAb9B7R4UxhBRCSlVRoJZCCYRqKGRRYJW8i8wcLGaBWsIgbmYSdia5Gk20LnEX+ABAwhph'
        b'BZRJawLI/lfi3ufe/Nc7Oa1Zxi5szcy/fc8/2ee47KavQM1ifGJaiQCADYIGGMzNwHEGAUNN8DwjGtEDFTxPeY1QJ'
        b'0GfGc0AfAJhBtIymDKSZgk/HJ8QLzPYsnUCBWgHXEpwXmBeO1yXjU8gitrJodzKVgGEj67VGCA2B+Nx7MOI9/iz6w'
        b'/brgOPBlNx7dOjC+2AWFwoakIgyrBsFh4KKkd4A74AvDM80Jia2s6bwAElLPhwi+37UjZCIiFFmgCCB4EfsGYgC6C'
        b'HwG/CD8K84yZq1lZyYWPtIU9AqwMftfeB4cDJ3geWDN9nlJr2aNXjZszUpRfUrtiJTesAu+l2KlIxfgoFxik7aeAr'
        b'fKM827Em9hnpbUdG29cWANEiMUmnk968b1NvDRv4FkzY4ab0/a0c6eCJjgfBMPamXVBOFLhp+EvhtWTdlfl9KjADO'
        b'jqKya4zbngMclQj+5nh/yryOG0zJvGk5JjMuq+Qq43LX1vQVFLDJIgvIUcCgB7RMifR1JbYQ/JLaAQzbHwI+Rd9qm'
        b'6Kc1aevbwPmHpKgAriCuYu8gnZ2M6+vLNIlg79H4oaxr613gDcEJpGHXLoPP8iwk9ohcVs3AcFrwJPB119Y/7xMkA'
        b'nf2O4TNMkXDqilkjtm+gHQOuAusDqvmJPi+WL6ViDwvFJ2GRJTYzNkhiWK5lVAivhEcNqwDnwM3sW9KwnaczQnn6h'
        b'OKTr0sAlPQa8BGn6JILj1BZ3uItCa8anNSYoB4Cfhz0d8WA6nvk7DuLlHU5z+ndrusmvdAv0g8i3l/Mq6/3Y/nf7A'
        b'gKRa5cYX+StfW28DH/wF0KYBtAngKHP2fYA+yJwRTlVVzDVjBrKM09DHRynNIs57P8oV5wCU3BEwQrCA+NGwWpJt7'
        b'BfFFf7MA53ffT6Kmb3IF7vERxj8Kvf0XZZBevdZw5vgAAAAASUVORK5CYII='
    )

    show_log = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACPElEQVRIiaWWv'
        b'W4TQRSFvzNauWIpSMsT0NlP4TegSBp3adNQBdkWLhAUtOnSJAU9QjyF8xJpQeKnstAeipnZnbV3jQVXsvZ49s6de8'
        b'89MzsCmF2snwCXNgvBc0TAxhJgZDqMADAk1MMN8AjcAjfbu+UvpeAfMfMYuJg5HugU+2x4GYBLYI4cjNsItjPo4bh'
        b'Mufwongsug80CCDE7bYzPgFqoNq6FethQA7XxED4DNjYYB9sLTS/W3wVP47o+e7hbfTudhUObXayfAV9THT8CEFJw'
        b'hHb/EzzZLtMlCJUceZf7XtPz1U+JSUttFBEps7LZy+396m1vsnPCUFlJeIqD2SRNgEkcp/UpYuS/1V5spM4xlN2Xy'
        b'wgexikzsa+ortDsA1DJRH68l6JUGyMLITK2emwh+H2wyikUYb8CQtuclIgSNypWmJ2vm+39cjNEUVWy2aMIXqc+YL'
        b'ublCOXbMo7YNOnKKKg1tN4X0qJ5xjbufby1UFiphu3XSpA9PIXb0CBATOpIre46TlILVWVDbn6Xg/Qu6GDzqlhBh7'
        b'ul8Mbs6XUVF0/vO8UN1pbUHrG1LJ0jx6uNkcpKtRcDOtQKUNOp1C0UzGqVv0p+2MLnELR9m5Zj0c4zTJFSQFCdJz/'
        b'qwkmBUVNRfyGvkjvr6bnqw9SPLYHVfS34HCVKbJ5rIgf6Pdp6rXEdXGel5Pjs6+icQyNxG0w3ACfQE13To7/cvloH'
        b'DtuvC/AjaC4tuCFrHhtGaPIbqWK2ceN0aOKa8sf0WEmVNYH1mUAAAAASUVORK5CYII='
    )

    start = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACPklEQVRIia2TP'
        b'2gUURDGf99xaAhWFmIVLMT+HhbWqcRKLES4tRdLIWATN0uKYJFKCxEbdQOKWAhCxMKAFv5BVi0ECxELCwmWQSRIPo'
        b't9t7d7uYt3SQYeM+y+nfnmN7MCCEl20vZjoa+IReBlkadb7IO1SufTkmYQs5hV4G5IsmMhyfangM1BMMYgpoAE/Ba'
        b'4GpJses8FJFoGBNgGDHDEsGT8KSTZ2U53ob37DqAlBAhJsVT15DjwSNKTTnchdLqTYStnYFqmUh69a9fcBs4gXgHL'
        b'IckOT1RAEqrnrmo4njKWmRa+YvtzSLLLIcmmxuugrAIIBEZYKp+pGcdz1HADWAtJNhu62cj5xBk05Yuovmdu4Iqzc'
        b'Qt8Clg13A9JNjMaEeoncT9JD1E9xnHT4phsHxC+UGJbyDoD82lVfjJE295LOmR0DXgdkuxcSMq1jj/arhCNik+AH9'
        b'o6D9Cuf9goouEx1R8Zrw+Ly8am+ohE1KHKjzqo1Fvh2R5/B10E7g100JQn96THgdZiSTgOv4ql34KbwHKRp+u9jO1'
        b'SuyqGla9jqcc1GtE2gafAXJGn3xiwdl35IN5hJvUa0pbt98LzQi+KPP077H67DmZcRIh10KKkO0We/tlBT+zAgMZA'
        b'ZDaQbguWijz9tVPiRgFVWzQCkdmUeI6YBz4WeTpO7n4Bm63+rjcRGX8RmgOejeI8RgfDtkg/DdeFbhUrO3P+fwd4U'
        b'xER9oakBzYZ4sckOEZ3gNaAS4J3oEXgzYeVvSXu2T998Bm7mZIDIAAAAABJRU5ErkJggg=='
    )

    stop = PyEmbeddedImage(
        b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAABSElEQVRIie2VT'
        b'U7DMBCFv2d5gXoEjsF5uEKFkDgA+657VxZVHwv/jUOTFonssJTkix175r1MYr28fn7Yekc8CRLlAAMiGSMD0tW1Xy'
        b'rDE8NV5VqncgFOGfQm8QzzKO1pFLgsSBuOHFq4PyabQ1vZuI/abjBxz7dns86GQ5aKJS1x20hDesu4sQ3IY71tzpn'
        b'quWrqinbcOPfx6MsGp66eKP++FfH5VTYpq3arexSuK0GM0YOcrWpPkO56vyi7qcW+NQZI4LTMUlXf6J6VlCr2XQbI'
        b'ilXRLfIUZBnwlxZp+mj2sGgx7a8tmmKHILrNc5Vts23yyEw/5t5q4wtvBb7NaVIfVMhDcmQq2/cZTBq/htE5XrqH9'
        b'IWuR/4UNv8WbTNoX4uA674WeWeLJF0yZfffxSLBVwZO4CPoIEh4sQ8zc9uz2360wRfQ+RtXGSpcSutTWgAAAABJRU'
        b'5ErkJggg=='
    )


if __name__ == "__main__":

    import pylint
    from tests.unit_tests.test_models.test_image_data import TestImageData

    TestImageData().run(True)
    pylint.run_pylint([__file__])
