"""
This file is automatically generated by the images/_generate_image_data.py script.
"""

from wx.lib.embeddedimage import PyEmbeddedImage


class ImageData(object):

    check_instruments = PyEmbeddedImage(
                            b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAG'
                            b'VKw4bAAADLElEQVRIiZ2WMWhkVRSGv//yCMFiCCnCIinCYrWFZF4hFltYKCgi6XRxZt'
                            b'WwpFBECxe0e/MQ2UJccFFsdklzVbQTG7GVTSHr23ULSSFiEUKKZQiLyBDC+y3um8ybT'
                            b'Qw7Oc07HM77zzn/PefcK4C8X84DrwPrwJNAZjtICgDYIAGEsW5AE72WXSMdArvAJhCr'
                            b'WIyU98p5xC3MJcQBeN+oFkkMLU1TlrHIydtykNVBzBu+B65kiLeAS5a3Za0jtgW1U0b'
                            b'IDbQ0VqbAjbFAJoAyy08JNoVeNfySYTYsRpjL1ddFdSy92eVO3htctnx7XMGyYIj0x1'
                            b'nQ0vn5qs0u4pu7cTACbQNDwXKGyRAj2/WZ8rXfsCgRCF7Ke4MriH/Bta25YByMEcwcI'
                            b'O+XF4BrMkEmYJ5HWoLUDuCQSQqeWGYBz4AvLS22fr8B/InJLEAKwRCaWmcBB3gH/JyA'
                            b'NBXcAT6rYkGiSwjI0rDMXMIq+GOc2lQwQmxUsXg4cUn9HSzhx0+evF8+AXxu1EECqQZ'
                            b'dq2Jx7xFskAjgNETTIEt5v1z8nxjvARcTLUbmV8T1KY+GIoAgRLuEbm/wDPh32791e+'
                            b'XT04EHq9glEJoU9xFvV7H4ZypAA2e7OWAdgS8hfWt0DmkF8UPeL1ebqjpGXyHNjcvH/'
                            b'gS4x6OiyXoJ9qQAiQPBMJVuBCvGP3b75QXwB9jPkuwYbyFuVLE4TqKP5oCQzinZqzjY'
                            b'B9aEquRhBMvYtzEftY7qgWCjioOD4+itOIZgqNstWsViF1jD3DdKIaQFS3ONXgMlnLK'
                            b'72hQdrYhWq1ax2EFaE9zXhK7xQP0M3DyRmglDiUa7DkDd7PTQdqpi8bfxyzZHdAFDYK'
                            b'OKxeg0atTwI6kOwKFQENMBAO7GwY6kV2y2QA9s3q9isXMaeCOZ0447DMAesACcP8mzi'
                            b'sWuxAu2u5LiY4CDWRF0MHvK++VV4FPwlq03Jf6qYnGmuyHvlwH7vMWm0EXDh+r2yo7E'
                            b'd4YXwftCw9RZR/fDVLD2Y6B5AoTxl6QvGhYEPxleE0DeKzuIdzHrhnPjfvdJgDbj+5/'
                            b'mNeOWg9CeYVP4iyoOHv4HTyN3/2iuEzYAAAAASUVORK5CYII='
                        )

    export_csv = PyEmbeddedImage(
                     b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAA'
                     b'ADV0lEQVRIiaWVT2hcVRTGf7/nUGKog4sQa5EsGhJLKaEziyKCot1YiLYg0k1mI0WoFuJCioiL'
                     b'mVmI+G8liJW60SkWhKLW4kosRerKiQRXQbroohWRUEVCCGE+F/PapJlpKHrgwrvv3vt99zvn3H'
                     b'NkiNUb7R2E+chxYNykQIsAhELpBXpAj3BFea3baS4Nw3IIeBHyAXFeWQGWSzCAnoEYjEVkXBgN'
                     b'XJPMJv66cLZ5B14xhHQfcEK5BnkiMCVMlmMqMiVOIZMkb5W3nAAuKjNbwSoD8GGfMgKc63Zavw'
                     b'yTvUntbyEQACaU7+qN9nPdTrO7nYKi77n8tR14eZt1Ee0PYDdwod5o76812tsRhGBvyNoWcx36'
                     b'u2/JCNlN8jVh+i4EKQDcCOx2tkLSs8RPgn2ePcrpWqNdGYhBbrkouQf8XEHnSMaQilgJPATMQ2'
                     b'bE8cEgQyGAAxk8YN1OawU4t/V/vdF6NnFXpHLXGPxPW5VgKKw12iPCaWBvoGKohowJN9E/ywPL'
                     b'JKAPAmtJ1tRRYB1YASohpxY6rW6p4OfgHqBWCLuAI8BBYA14EalFPwXqCZdJjiMvAyNJrgpvBq'
                     b'ZDrgLtwEHwsc0SBAxUUk5IVtCjyAHxHcgjCcvoe8RDgaMmE8gqcVGyGPiSMCbZGb3t7r7YPvBt'
                     b'f0cXFzrNP4C3A8eCj6M7hRnkW5KfohVxPzJO/IH4I2QWxU1x041ZYVnvTFk2wj8QTBBGQr4AXl'
                     b'E/Fs6TjAJPYs4oq5FDSSBsUpB+LejnfHolw4F6o70fmRNfQj8j+Rt4tQxykfISSWa7ndb1hLpx'
                     b'QobkXemmonzuPfqP5ALJC8Bywki0MFSBq+gbyvMo6FP1uVZDORnZ0XcRa3e4SAj0KsDvIa+Ljx'
                     b'oK8JmQw+pl4BN0Epgsz360EUBrwHXhfWAV/Wqzi0AQKt1OswecubVYm2s1hMMJFxfONt/dqvxe'
                     b'zE1VYKBUqOsBdEivuEdLWUTNsIZD1kuq+/8rgTAC9MJQApcka0mO1RvtzwlL3S199m5Wn2sXwB'
                     b'GS6cCieH1Y069APkw4gd4EloW12y+ejZR08LsQJsq9c91O8/x9WwluLF7qPTzz9Pf2U28vZEys'
                     b'AlWhmqSqVIEq4Y5v5AFwyXAS+ebG4qX8C7bLc9zJ6EyLAAAAAElFTkSuQmCC'
                 )

    open_config = PyEmbeddedImage(
                      b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bA'
                      b'AACOElEQVRIidWVP2sUURTFf2cYJIUsQSzEQlJIsAq4WCmkELGwEAu7HRE/gqRKNTN+AbuAoE'
                      b'h0FxQbC0kl+QBBdmGxtIgiIYgasJAQljkWb2ZnNmyTsdFbzLu8+979c867d+B/FwF0kxzgLPg'
                      b'0KMJEiAlwaPNtNEiL1gG6Sb5kvIlZlcAGKRiNAH8S6g376U6bAJHNY1mrkgBRraDqexF41k2y'
                      b'TrsKevkPxBmX+QbnrsxlKS5AqWFfogAK20VIhgIDYgyMh/30eIDsALFYHgIL5DrGHKmONnVDI'
                      b'SkHPxr2sxoiKkima8DeKvc0q8/bs4SkCFizuTRbQZIfAIvHc7Nd8jGrz+Q8F1K/N9oVfAY24n'
                      b'D52D2VfNg1E64xq/maq98QDiGla3FZWg2qwLAPWkfsEkgsKnsAsq600oNLRYZI0BE8B67ETcL'
                      b'K9Auhh8NB+oqW0k3ym0AH2IpmnQPwBdhq6xzA9j0gMryMgQBRWSz229Eg+9XWeTfJO8Btw55g'
                      b'O2pwh2AiafAXyYO5g93Bfjfspz+j6esLNH3AfGzr+3Ivj43vIyaSNgHi2iwEb4aD9LBtAIll0'
                      b'FVgbHsMAf9qFE+MW7+cUu7aXgBejwbZ7xDAHJXG7VE/22vruZvkF4AHQkfAi2o/BnaAW8C5bp'
                      b'I9KZsqVGVVbdzQpxI11gXgus158NNRP9uvA4g1YAlYMaxIoSs17UA3RlSlK8wnGrp0BN5AWm9'
                      b'mUf0yTwHLhrg5lk4oX4f99PvJr/3r8gex6e+LR2Pc0wAAAABJRU5ErkJggg=='
                  )

    save_config = PyEmbeddedImage(
                      b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bA'
                      b'AACRUlEQVRIia2WMWsUQRzFf29YrghBJFiISLgitXBXWfgVIoltrhOsBLG0yl3hJwgWNlaJXy'
                      b'BgYS2oCEmTykKCiKQIQTAEkWOfxczu7G2iG8m9apibee//3vxn5zQcTa4bPxdaAxaAYHOMPMU'
                      b'ggYmQKQ1Iwo4/CrDpSSwB7zBP9nY2v1DtGWyMtyQ9JuOD8TroNxdAgKEQLIOD0ang2OalxJrN'
                      b'ocQqcLC3vUmBdD9uNY4Eh/vb46OLyCsMR5MV4CMQBK/2tjcfDjYmnwEk+sa7QqvAQVCMpSLPe'
                      b'fwDjuUEz6z11DhGZ/qY3cFovFIAIVpXlUHZJSA7INV5tfZX6Au2gpOAU12XsqCKJa93KswzHL'
                      b'pXyARklDKyux04ZaOGmBzJs3QcF1ayVzmUQ7eBnEN9DlEtn2VCgCahAd0YjiZdGt9trxvWwS+'
                      b'SqyXVEtmJhhvjn4jFLK0S+8DwA7rjSugJ7jq2bS4VTgun29jwFSzdaU61bTdTabfERRGd2xrv'
                      b'Q2Pes2vaUfxtDFAo650YBpgT5FKorOqJh9quDYgdErDKVFkALQKfgGXbFI3CjvZ3xl+5Os6Go'
                      b'8k3w7Ik6utuPJ0DeQ0l1qC6/3XZjulEdWJOn4m5EVcQ+d2oL5ndbrgriwDODprX/6pw9QFsRj'
                      b'Tv+psRRQfzVWhEZP9KM51f0f9ASPzTAumN4ZHg5mA0uS04S4vK9uVNfyTOo35LHIR6hlsxIt4'
                      b'WwDNBATwQvDecyi4zccrTIMVnREkpzqexjUQwLAiu2X6N9PQPhTEDM93XSYAAAAAASUVORK5C'
                      b'YII='
                  )

    settings = PyEmbeddedImage(
                   b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC'
                   b'/0lEQVRIia2Vv4sdVRTHP9/L8JAYgoQlKAb9B7R4UxhBRCSlVRoJZCCYRqKGRRYJW8i8wcLGaBWs'
                   b'IgbmYSdia5Gk20LnEX+ABAwhphBZRJawLI/lfi3ufe/Nc7Oa1Zxi5szcy/fc8/2ee47KavQM1ifG'
                   b'JaiQCADYIGGMzNwHEGAUNN8DwjGtEDFTxPeY1QJ0GfGc0AfAJhBtIymDKSZgk/HJ8QLzPYsnUCBW'
                   b'gHXEpwXmBeO1yXjU8gitrJodzKVgGEj67VGCA2B+Nx7MOI9/iz6w/brgOPBlNx7dOjC+2AWFwoak'
                   b'IgyrBsFh4KKkd4A74AvDM80Jia2s6bwAElLPhwi+37UjZCIiFFmgCCB4EfsGYgC6CHwG/CD8K84y'
                   b'Zq1lZyYWPtIU9AqwMftfeB4cDJ3geWDN9nlJr2aNXjZszUpRfUrtiJTesAu+l2KlIxfgoFxik7ae'
                   b'ArfKM827Em9hnpbUdG29cWANEiMUmnk968b1NvDRv4FkzY4ab0/a0c6eCJjgfBMPamXVBOFLhp+E'
                   b'vhtWTdlfl9KjADOjqKya4zbngMclQj+5nh/yryOG0zJvGk5JjMuq+Qq43LX1vQVFLDJIgvIUcCgB'
                   b'7RMifR1JbYQ/JLaAQzbHwI+Rd9qm6Kc1aevbwPmHpKgAriCuYu8gnZ2M6+vLNIlg79H4oaxr613g'
                   b'DcEJpGHXLoPP8iwk9ohcVs3AcFrwJPB119Y/7xMkAnf2O4TNMkXDqilkjtm+gHQOuAusDqvmJPi+'
                   b'WL6ViDwvFJ2GRJTYzNkhiWK5lVAivhEcNqwDnwM3sW9KwnaczQnn6hOKTr0sAlPQa8BGn6JILj1B'
                   b'Z3uItCa8anNSYoB4Cfhz0d8WA6nvk7DuLlHU5z+ndrusmvdAv0g8i3l/Mq6/3Y/nf7AgKRa5cYX+'
                   b'StfW28DH/wF0KYBtAngKHP2fYA+yJwRTlVVzDVjBrKM09DHRynNIs57P8oV5wCU3BEwQrCA+NGwW'
                   b'pJt7BfFFf7MA53ffT6Kmb3IF7vERxj8Kvf0XZZBevdZw5vgAAAAASUVORK5CYII='
               )

    show_log = PyEmbeddedImage(
                   b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC'
                   b'PElEQVRIiaWWvW4TQRSFvzNauWIpSMsT0NlP4TegSBp3adNQBdkWLhAUtOnSJAU9QjyF8xJpQeKn'
                   b'stAeipnZnbV3jQVXsvZ49s6de889MzsCmF2snwCXNgvBc0TAxhJgZDqMADAk1MMN8AjcAjfbu+Uv'
                   b'peAfMfMYuJg5HugU+2x4GYBLYI4cjNsItjPo4bhMufwongsug80CCDE7bYzPgFqoNq6FethQA7Xx'
                   b'ED4DNjYYB9sLTS/W3wVP47o+e7hbfTudhUObXayfAV9THT8CEFJwhHb/EzzZLtMlCJUceZf7XtPz'
                   b'1U+JSUttFBEps7LZy+396m1vsnPCUFlJeIqD2SRNgEkcp/UpYuS/1V5spM4xlN2Xywgexikzsa+o'
                   b'rtDsA1DJRH68l6JUGyMLITK2emwh+H2wyikUYb8CQtuclIgSNypWmJ2vm+39cjNEUVWy2aMIXqc+'
                   b'YLublCOXbMo7YNOnKKKg1tN4X0qJ5xjbufby1UFiphu3XSpA9PIXb0CBATOpIre46TlILVWVDbn6'
                   b'Xg/Qu6GDzqlhBh7ul8Mbs6XUVF0/vO8UN1pbUHrG1LJ0jx6uNkcpKtRcDOtQKUNOp1C0UzGqVv0p'
                   b'+2MLnELR9m5Zj0c4zTJFSQFCdJz/qwkmBUVNRfyGvkjvr6bnqw9SPLYHVfS34HCVKbJ5rIgf6Pdp'
                   b'6rXEdXGel5Pjs6+icQyNxG0w3ACfQE13To7/cvloHDtuvC/AjaC4tuCFrHhtGaPIbqWK2ceN0aOK'
                   b'a8sf0WEmVNYH1mUAAAAASUVORK5CYII='
               )

    start = PyEmbeddedImage(
                b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAACPkl'
                b'EQVRIia2TP2gUURDGf99xaAhWFmIVLMT+HhbWqcRKLES4tRdLIWATN0uKYJFKCxEbdQOKWAhCxMKAFv'
                b'5BVi0ECxELCwmWQSRIPot9t7d7uYt3SQYeM+y+nfnmN7MCCEl20vZjoa+IReBlkadb7IO1SufTkmYQs'
                b'5hV4G5IsmMhyfangM1BMMYgpoAE/Ba4GpJses8FJFoGBNgGDHDEsGT8KSTZ2U53ob37DqAlBAhJsVT1'
                b'5DjwSNKTTnchdLqTYStnYFqmUh69a9fcBs4gXgHLIckOT1RAEqrnrmo4njKWmRa+YvtzSLLLIcmmxuu'
                b'grAIIBEZYKp+pGcdz1HADWAtJNhu62cj5xBk05Yuovmdu4IqzcQt8Clg13A9JNjMaEeoncT9JD1E9xn'
                b'HT4phsHxC+UGJbyDoD82lVfjJE295LOmR0DXgdkuxcSMq1jj/arhCNik+AH9o6D9Cuf9goouEx1R8Zr'
                b'w+Ly8am+ohE1KHKjzqo1Fvh2R5/B10E7g100JQn96THgdZiSTgOv4ql34KbwHKRp+u9jO1SuyqGla9j'
                b'qcc1GtE2gafAXJGn3xiwdl35IN5hJvUa0pbt98LzQi+KPP077H67DmZcRIh10KKkO0We/tlBT+zAgMZ'
                b'AZDaQbguWijz9tVPiRgFVWzQCkdmUeI6YBz4WeTpO7n4Bm63+rjcRGX8RmgOejeI8RgfDtkg/DdeFbh'
                b'UrO3P+fwd4UxER9oakBzYZ4sckOEZ3gNaAS4J3oEXgzYeVvSXu2T998Bm7mZIDIAAAAABJRU5ErkJgg'
                b'g=='
            )

    stop = PyEmbeddedImage(
               b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAABSElE'
               b'QVRIie2VTU7DMBCFv2d5gXoEjsF5uEKFkDgA+657VxZVHwv/jUOTFonssJTkix175r1MYr28fn7Yekc8'
               b'CRLlAAMiGSMD0tW1XyrDE8NV5VqncgFOGfQm8QzzKO1pFLgsSBuOHFq4PyabQ1vZuI/abjBxz7dns86G'
               b'Q5aKJS1x20hDesu4sQ3IY71tzpnquWrqinbcOPfx6MsGp66eKP++FfH5VTYpq3arexSuK0GM0YOcrWpP'
               b'kO56vyi7qcW+NQZI4LTMUlXf6J6VlCr2XQbIilXRLfIUZBnwlxZp+mj2sGgx7a8tmmKHILrNc5Vts23y'
               b'yEw/5t5q4wtvBb7NaVIfVMhDcmQq2/cZTBq/htE5XrqH9IWuR/4UNv8WbTNoX4uA674WeWeLJF0yZfff'
               b'xSLBVwZO4CPoIEh4sQ8zc9uz2360wRfQ+RtXGSpcSutTWgAAAABJRU5ErkJggg=='
           )


if __name__ == '__main__':

    import wx

    _app = wx.App(redirect=False)

    print(ImageData.check_instruments.Bitmap)
    print(ImageData.export_csv.Bitmap)
    print(ImageData.open_config.Bitmap)
    print(ImageData.save_config.Bitmap)
    print(ImageData.settings.Bitmap)
    print(ImageData.show_log.Bitmap)
    print(ImageData.start.Bitmap)
    print(ImageData.stop.Bitmap)
